name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Hugo tarball
        run: |
          wget -q https://github.com/gohugoio/hugo/releases/download/v0.101.0/hugo_0.101.0_Linux-64bit.tar.gz
      - name: Extract Hugo
        run: tar -xf hugo_0.101.0_Linux-64bit.tar.gz hugo
      - name: Generate files
        run: ./hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: laur.pro
